name: TEST Deploy LBP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.x.x'

    - name: Build with dotnet
      run: dotnet build LB.PhotoGalleries/LB.PhotoGalleries.csproj --configuration Release

    - name: dotnet Publish
      run: dotnet publish LB.PhotoGalleries/LB.PhotoGalleries.csproj --configuration Release
      
    - name: Remove server specific config files
      run: sudo rm -f /home/runner/work/PhotoGalleries/PhotoGalleries/LB.PhotoGalleries/bin/Release/net9.0/publish/appsettings*

    - name: Copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.TEST_REMOTE_HOST }}
        port: ${{ secrets.TEST_PORT }}
        username: ${{ secrets.TEST_REMOTE_USER }}
        key: ${{ secrets.TEST_SSH_KEY }}
        passphrase: ${{ secrets.TEST_SSH_KEY_PASSPHRASE }}
        strip_components: 10
        source: "/home/runner/work/PhotoGalleries/PhotoGalleries/LB.PhotoGalleries/bin/Release/net9.0/publish/*"
        target: "${{ secrets.TEST_REMOTE_DIR }}"
        overwrite: true
